
parameters:
  - name: solutionPath
    type: string
    default: ""
  - name: bicepLint
    type: boolean
    default: true

stages:
- stage: Build
  jobs:
  - job: BicepBuild
    pool: { vmImage: 'ubuntu-latest' }
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: "Install Bicep"
        inputs:
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az bicep install
      - script: |
          find ${{ parameters.solutionPath || '.' }} -name '*.bicep' -print -exec az bicep build --file {} \;
        displayName: "Build all Bicep files"
